title: Benjamin Chait
email: hello+www@benjaminchait.net
description: Benjamin’s site
url: "https://benjaminchait.net"
twitter_username: benjaminchait
github_username: benjaminchait
timezone: America/Los_Angeles

plugins:
  - jekyll-sitemap

include:
  - _redirects
  - .well-known
